title: Dylan Kaplan # your name (or website title) here
logo: "/images/dylankaplan.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  Reading the world through data.
  <br><br>Orland, Florida | University of Central Florida Industrial Engineering
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
