title:                 Dylan Kaplan # your name (or website title) here
logo: "/images/profilepic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  <br>Data Science
  <br><br>Orlando, Florida 
  <br>University of Central Florida 
  <br>Industrial Engineering
  <br>
  
  <br><a href="https://www.linkedin.com/in/dylan-kaplan-856818128/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-154991636-1 # your Google Analytics tracking ID here
