title: Dylan Kaplan # your name (or website title) here
logo: "/images/profilepic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  <br>Interested in all-things Data
  <br><br>Orlando, Florida 
  <br>University of Central Florida 
  <br>Industrial Engineering
  <br><br>Contact Information:
  <br>863-529-4326
  <br>dsk0203@gmail.com
  
  <br><br><a href="https://www.linkedin.com/in/dylan-kaplan-856818128/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
